/**
 * Ambient typing for the wasm-pack output (`pkg/`), which is generated by
 * `just build_soup_filter_wasm` and not committed. Keeping the declaration
 * ambient lets this package typecheck before the artifact has been built.
 *
 * The shape mirrors `rust/cloud-storage/soup_filter_wasm/src/lib.rs`; if the
 * Rust API changes, update this declaration alongside it (the generated
 * `pkg/soup_filter_wasm.d.ts` is the reference).
 */
declare module '*/pkg/soup_filter_wasm' {
  /** 0 = NoMatch, 1 = Match, 2 = Unknown */
  export type VerdictCode = 0 | 1 | 2;

  export class SoupFilter {
    /** Compile from the `POST /items/soup/ast` body shape. */
    static fromAst(astJson: string, currentUserId?: string): SoupFilter;
    /** Compile from the `POST /items/soup` typed-filters body shape. */
    static fromTypedFilters(filtersJson: string, currentUserId?: string): SoupFilter;
    /** Evaluate one SoupApiItem JSON string. */
    matches(soupItemJson: string): VerdictCode;
    /** Evaluate a JSON array of SoupApiItems in one boundary crossing. */
    matchesMany(soupItemsJson: string): Uint8Array;
    /** The canonical expanded AST JSON (the `POST /items/soup/ast` body). */
    astJson(): string;
    free(): void;
  }
}
