[package]
edition = "2024"
name = "email_service_client"
publish = false
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
email = { path = "../email", features = ["axum", "inbound"] }
models_email = { path = "../models_email" }
reqwest = { workspace = true }
tracing = { workspace = true }
