[package]
name = "scheduled_action"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "scheduled_action_openapi"
path = "src/bins/openapi.rs"

[features]
default = []
toolset = ["dep:async-trait", "dep:schemars"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
macro_env_var = { path = "../macro_env_var" }
sqlx = { workspace = true }
macro_user_id = { path = "../macro_user_id"}
cron = { version = "0.16.0" }
anyhow = { workspace = true }
macro_uuid = { path = "../macro_uuid"}
chrono = { workspace = true}
chrono-tz = { version = "0.10.4", features = ["serde"] }
ai = { path = "../ai" }
ai_toolset = { path = "../ai_toolset" }
async-trait = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
tokio = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
axum = { workspace = true }
model_user = { path = "../model_user", features = ["axum"] }
connection_gateway_client = { path = "../connection_gateway_client" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
utoipa = { workspace = true, features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { workspace = true }
