[package]
edition = "2024"
name = "entity_access_management"
publish = false
version = "0.1.0"

[features]
default = ["outbound", "ports"]
outbound = [
  "dep:entity_access_db_utils",
  "dep:sqlx",
  "models_entity_access_management/db",
  "ports",
]
ports = []

[dependencies]
# Core
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
model-entity = { path = "../model-entity" }
models_entity_access_management = { path = "../models_entity_access_management", default-features = false }
models_permissions = { path = "../models_permissions" }

# Database
entity_access_db_utils = { path = "../entity_access_db_utils", optional = true }
sqlx = { workspace = true, optional = true }

[dev-dependencies]
macro_db_migrator = { path = "../macro_db_migrator" }
sqlx = { workspace = true, features = ["postgres", "runtime-tokio-rustls"] }
