#!/usr/bin/env python3
"""Generate .github/workspace-dep-closures.json from `cargo metadata`.

For every member of the rust/cloud-storage workspace, record the directories
(relative to the workspace root) of the member itself plus every workspace
crate in its transitive dependency closure. flake.nix uses this map to give
each deploy artifact (service binary / lambda handler) a pruned source tree:
only the crates the artifact actually depends on keep their real sources,
every other member is reduced to its manifest plus a stub target. The
artifact's nix store hash then only changes when a crate in its closure
changes, so a change to e.g. an email-only crate leaves the unrelated
deploy derivations as pure cache hits.

Edges follow normal and build dependencies but NOT dev-dependencies: deploy
artifacts are built with `cargo build --bin`, which never compiles dev-deps,
and including them would only widen closures (more invalidation, never more
correctness). The metadata is resolved with --all-features so optional
workspace deps are always included — a superset closure is sound (worst case
a leaf rebuilds when it didn't need to, or carries sources it never reads);
a missing crate would fail the build loudly inside the nix sandbox.

Run from the repo root:

    python3 .github/scripts/generate-workspace-dep-closures.py

CI regenerates the file and fails on drift (see
.github/workflows/cargo-workspace-dependency-check.yml).
"""

import json
import pathlib
import subprocess
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
WORKSPACE = REPO_ROOT / "rust" / "cloud-storage"
OUTPUT = REPO_ROOT / ".github" / "workspace-dep-closures.json"


def main() -> int:
    meta = json.loads(
        subprocess.check_output(
            [
                "cargo",
                "metadata",
                "--format-version",
                "1",
                "--all-features",
                "--locked",
            ],
            cwd=WORKSPACE,
        )
    )

    members = set(meta["workspace_members"])
    packages = {p["id"]: p for p in meta["packages"]}

    # Member-to-member edges, excluding dev-only dependencies.
    edges: dict[str, list[str]] = {}
    for node in meta["resolve"]["nodes"]:
        if node["id"] not in members:
            continue
        deps = []
        for dep in node["deps"]:
            if dep["pkg"] not in members:
                continue
            if not any(k["kind"] in (None, "build") for k in dep["dep_kinds"]):
                continue
            deps.append(dep["pkg"])
        edges[node["id"]] = deps

    def rel_dir(pkg_id: str) -> str:
        manifest_dir = pathlib.Path(packages[pkg_id]["manifest_path"]).parent
        return manifest_dir.relative_to(WORKSPACE).as_posix()

    closures: dict[str, list[str]] = {}
    for root in members:
        seen = {root}
        stack = [root]
        while stack:
            for dep in edges.get(stack.pop(), []):
                if dep not in seen:
                    seen.add(dep)
                    stack.append(dep)
        closures[packages[root]["name"]] = sorted(rel_dir(p) for p in seen)

    doc = {
        "//": (
            "Generated by .github/scripts/generate-workspace-dep-closures.py; "
            "do not edit by hand. Maps every rust/cloud-storage workspace "
            "crate to the directories of its transitive workspace dependency "
            "closure (normal + build deps, dev-deps excluded). Consumed by "
            "flake.nix to build pruned per-artifact deploy sources."
        ),
        "closures": dict(sorted(closures.items())),
    }
    OUTPUT.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(closures)} members)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
