FROM ubuntu:noble AS base
ARG SERVICE_NAME=convert_service
WORKDIR /app

# Accept the Microsoft core fonts license
RUN printf '%s\n' "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" > /tmp/ms-fonts-selections \
  && debconf-set-selections /tmp/ms-fonts-selections \
  && rm /tmp/ms-fonts-selections

RUN : \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
  tar \
  libreoffice \
  libreofficekit-dev \
  ca-certificates \
  openssl \
  dumb-init \
  libkrb5-3 \
  ttf-mscorefonts-installer \
  wget xfonts-utils \
  cabextract \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

RUN fc-cache -f -v

COPY vendor/core-co-25.04-assets.tar.gz.part-* /tmp/core-co-25.04-assets-parts/
RUN cat /tmp/core-co-25.04-assets-parts/core-co-25.04-assets.tar.gz.part-* > core-co-25.04-assets.tar.gz \
  && echo "7331fbfcc6999c5cf279d50011a9b0614d0dc6f32823b5716c5daef639651822  core-co-25.04-assets.tar.gz" | sha256sum -c - \
  && tar -xvf core-co-25.04-assets.tar.gz \
  && mkdir -p /app/lok \
  && mv instdir /app/lok/instdir \
  && mv include /app/lok/include \
  && rm -r core-co-25.04-assets.tar.gz /tmp/core-co-25.04-assets-parts

COPY ./prebuilt/nix-store/ /nix/store/
COPY ./prebuilt/${SERVICE_NAME} /app/svc
RUN chmod +x /app/svc

ENV PORT=8080
EXPOSE ${PORT}
ENTRYPOINT ["dumb-init", "./svc"]
