[package]
edition = "2024"
name = "properties_service"
publish = false
version = "0.1.0"

[lib]
name = "properties_service"
path = "src/lib.rs"

[[bin]]
name = "properties_service_openapi"
path = "src/openapi.rs"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true, features = ["tower-log", "ws"] }
chrono = { workspace = true }
email_db_client = { path = "../email_db_client" }
entity_access = { path = "../entity_access" }
macro_user_id = { path = "../macro_user_id" }
model-entity = { path = "../model-entity" }
macro_middleware = { path = "../macro_middleware", default-features = false, features = [
  "auth",
  "cloud_storage",
] }
notification = { path = "../notification" }
macro_uuid = { path = "../macro_uuid" }
model = { path = "../model" }
models_permissions = { path = "../models_permissions" }
models_properties = { path = "../models_properties" }
properties_db_client = { path = "../properties_db_client" }
properties = { path = "../properties" }
system_properties = { path = "../system_properties" }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
