[package]
name = "scheduled_action_service"
version = "0.1.0"
edition = "2024"
publish = false

[features]
default = []
local_auth = ["macro_middleware/local_auth"]

[dependencies]
scheduled_action = { path = "../scheduled_action" }
ai = { path = "../ai" }
ai_tools = { path = "../ai_tools" }
ai_toolset = { path = "../ai_toolset" }
anyhow = { workspace = true }
axum = { workspace = true }
aws-sdk-sqs = { workspace = true }
aws-sdk-secretsmanager = { workspace = true }
chat = { path = "../chat" }
chrono = { workspace = true }
connection_gateway_client = { path = "../connection_gateway_client" }
futures = { workspace = true }
macro_auth = { path = "../macro_auth" }
macro_aws_config = { path = "../macro_aws_config" }
macro_cors = { path = "../macro_cors" }
macro_db_client = { path = "../macro_db_client" }
macro_entrypoint = { path = "../macro_entrypoint" }
macro_env = { path = "../macro_env" }
macro_env_var = { path = "../macro_env_var" }
macro_middleware = { path = "../macro_middleware", default-features = false, features = [
  "auth",
] }
macro_user_id = { path = "../macro_user_id" }
memory = { path = "../memory" }
model = { path = "../model" }
model-entity = { path = "../model-entity" }
model_notifications = { path = "../model_notifications" }
notification = { path = "../notification" }
secretsmanager_client = { path = "../secretsmanager_client" }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras", "chrono"] }
utoipa-swagger-ui = { workspace = true }
